const FETCHING_START = "FETCHING_START";
const FETCHING_SUCCESS = "FETCHING_SUCCESS";
const FETCHING_FAIL = "FETCHING_FAIL";
const SET_PARKS = "SET_PARKS";


export const actions={
    FETCHING_START,
    FETCHING_SUCCESS,
    FETCHING_FAIL,
    SET_PARKS,
}